# utils/email_template.py

from datetime import datetime

class TemplateGenerator:
    def __init__(self):
        pass

    def generate_template(self, meeting_topic, speaker_name, meeting_date, meeting_time,
                          duration, location, meeting_link, attendees, additional_notes,
                          priority="Medium", template_type="formal_internal"):
        # Simple example to generate a basic HTML email content with inline CSS
        current_date = datetime.now().strftime("%d %b %Y")
        
        # Priority color map
        priority_colors = {
            "Low": "#28a745",
            "Medium": "#ffc107",
            "High": "#dc3545",
            "Urgent": "#dc3545"
        }
        priority_color = priority_colors.get(priority, "#ffc107")

        attendees_str = ", ".join(attendees) if isinstance(attendees, list) else attendees

        html_content = f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
            <div style="background: #667eea; color: white; padding: 20px;">
                <h2 style="margin: 0;">Meeting Invitation</h2>
                <p style="margin: 0;">{meeting_topic}</p>
            </div>
            <div style="padding: 20px; background: #f9f9f9;">
                <p><strong>Speaker:</strong> {speaker_name}</p>
                <p><strong>Date:</strong> {meeting_date}</p>
                <p><strong>Time:</strong> {meeting_time}</p>
                <p><strong>Duration:</strong> {duration}</p>
                <p><strong>Location:</strong> {location}</p>
                <p><strong>Priority:</strong> <span style="color: {priority_color}; font-weight: 700;">{priority}</span></p>
                {"<p><strong>Meeting Link:</strong> <a href='" + meeting_link + "'>" + meeting_link + "</a></p>" if meeting_link else ""}
                <p><strong>Attendees:</strong> {attendees_str}</p>
                <p><strong>Notes:</strong></p>
                <p>{additional_notes or 'No additional notes.'}</p>
            </div>
            <div style="background: #eee; text-align: center; padding: 10px; font-size: 12px; color: #666;">
                Generated by SmartMeetingAI
            </div>
        </div>
        """
        subject = f"Meeting Invitation: {meeting_topic}"
        return {
            "subject": subject,
            "content": html_content
        }
